#!/bin/bash

qemu-system-aarch64 \
    -machine virt,virtualization=true,gic-version=3 \
    -nographic \
    -m size=1024M \
    -net nic -net tap,ifname=tap0,script=no,downscript=no \
    -drive format=raw,file=rootfs.img \
    -append "root=/dev/vda rw kgdboc=ttyAMA0,115200" \
    -kernel Image.gz \
    -smp 2 \
    -hdb share.img \
    -cpu cortex-a53


